#!/bin/bash

# This script runs the Axolotl fine-tuning process.

# Ensure the config file exists
if [ ! -f "config.yaml" ]; then
    echo "Error: config.yaml not found in the current directory."
    echo "Make sure you are in the root directory of the project and the file exists."
    exit 1
fi

# Ensure the dataset file exists as per the config
# This is a basic check, Axolotl will do its own more thorough validation.
DATASET_PATH=$(grep 'path:' config.yaml | sed 's/.*path: //') # Extracts path from config
if [ ! -f "$DATASET_PATH" ]; then
    echo "Error: Dataset file $DATASET_PATH (specified in config.yaml) not found."
    echo "Please ensure the dataset is generated by running scripts/chunk_text.py first."
    exit 1
fi

echo "Starting Axolotl fine-tuning..."
echo "Using configuration: config.yaml"
echo "Output will be saved to the directory specified in config.yaml (./output by default)."

# Command to run Axolotl
# Ensure Axolotl is installed and accessible in your environment.
if ! command -v axolotl >/dev/null 2>&1; then
    echo "Error: Axolotl CLI not found. Please install it and ensure it is in your PATH."
    exit 1
fi

axolotl train ./config.yaml

# Check exit status of Axolotl
if [ $? -eq 0 ]; then
    echo "Axolotl fine-tuning completed successfully."
else
    echo "Error: Axolotl fine-tuning failed. Check the logs for details."
    exit 1
fi

echo "You can find the trained model artifacts in the './output' directory (or as configured in config.yaml)."
